Added URL
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -36,8 +36,9 @@ jobs:
         env:
           USERNAME: bateel-automation-demo
           PASSWORD: LaQSZC0byfgE4fxG
+          PORT: 2255
         run: |
               # Loop through each file in the allure-results directory and upload it
               for file in ./allure-results/*; do
-                  curl -u "$USERNAME:$PASSWORD" -X POST -F "file=@$file" "https://bateel-automation-demo.magentoprojects.net/upload" || { echo "Failed to upload $file"; exit 1; }
+                  scp -P "$PORT" "$file" "$USERNAME@bateel-automation-demo.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload $file"; exit 1; }
               done
