updated YML
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -1,35 +1,35 @@
 name: CI/CD Pipeline
-
+ 
 on:
   push:
     branches:
       - main
       - dockerIntegration
-
+ 
 jobs:
   build:
     runs-on: ubuntu-latest
-
+ 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
-
+ 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
-
+ 
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '16'
-
+ 
       - name: Install Allure Commandline
         run: |
           npm install -g allure-commandline --save-dev
-
+ 
       - name: Build Docker Image
         run: |
           docker build -t hamleys-automation .
-
+ 
       - name: Ensure Allure Environment File Exists
         run: |
           mkdir -p allure-results  # Create directory if it doesn't exist
@@ -37,11 +37,11 @@ jobs:
             echo "Creating an empty env.properties file."
             echo "Not specified" > allure-results/env.properties
           fi
-
+ 
       - name: Clean Allure Results in Container
         run: |
           docker run --rm hamleys-automation /bin/sh -c "rm -rf /usr/share/HamleysAutomation/allure-results/*"
-
+ 
       - name: Run Tests and Generate Allure Report
         run: |
           docker run --name hamleys-automation \
@@ -49,7 +49,7 @@ jobs:
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v ${{ github.workspace }}/allure-results:/usr/share/HamleysAutomation/allure-results \
           hamleys-automation /bin/sh -c "Xvfb :99 -screen 0 1920x1080x24 & DISPLAY=:99 mvn clean test -X"
-
+ 
       - name: Check Test Execution Exit Code
         run: |
           EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' hamleys-automation)
@@ -61,28 +61,27 @@ jobs:
             exit 1
           fi
           docker rm hamleys-automation  # Ensure the container is removed after checking
-
+ 
       - name: Inspect Allure Results
         run: |
           echo "Contents of allure-results:"
           ls -la allure-results
-
+ 
       - name: Generate Allure HTML Report
         run: |
-          TIMESTAMP=$(date +%Y%m%d%H%M%S)
-          allure generate allure-results --output ./allure-report/$TIMESTAMP --clean
-
+          allure generate allure-results --output ./allure-report --clean
+ 
       - name: Upload Allure Report
         uses: actions/upload-artifact@v3
         with:
           name: allure-report
-          path: ./allure-report/$TIMESTAMP
-
+          path: ./allure-report
+ 
       - name: Install sshpass
         run: |
           sudo apt-get update
           sudo apt-get install -y sshpass
-
+ 
       - name: Publish Allure Report to Server
         env:
           USERNAME: bateel-automation-demo
@@ -90,8 +89,4 @@ jobs:
           SERVER: bateel-automation-demo.magentoprojects.net
           PORT: 2255
         run: |
-          # Remove existing report files on the server
-          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@$SERVER" "rm -rf /var/www/html/bateel-automation-demo/webroot/*"
-          
-          # Upload new report files
-          sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/$TIMESTAMP/* "$USERNAME@$SERVER:/var/www/html/bateel-automation-demo/webroot/" || { echo "Failed to upload files"; exit 1; }
+          sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/* "$USERNAME@$SERVER:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload files"; exit 1; }
