Added sshpass section
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -27,25 +27,19 @@ jobs:
 
       - name: Save Allure Report to Local Directory
         run: |
-          docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results
-
-      - name: Add SSH Key
+            docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results
+        
+      - name: Install sshpass
         run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
-          chmod 600 ~/.ssh/id_ed25519
-
-      - name: Add SSH Known Hosts
-        run: |
-          ssh-keyscan -H -p 2255 /var/www/html/bateel-automation-demo/.ssh
-
+            sudo apt-get update
+            sudo apt-get install -y sshpass
+        
       - name: Upload Allure Report to Docker Container
         env:
-          USERNAME: bateel-automation-demo
-          PORT: 2255
+            USERNAME: bateel-automation-demo
+            PASSWORD: ${{ secrets.SSH_PASSWORD }} # Store your password as a GitHub secret
+            PORT: 2255
         run: |
-          eval "$(ssh-agent -s)"
-          ssh-add ~/.ssh/id_ed25519
-          for file in ./allure-results/*; do
-            scp -P "$PORT" -o IdentitiesOnly=yes "$file" "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload $file"; exit 1; }
-          done
+            for file in ./allure-results/*; do
+              sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no "$file" "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload $file"; exit 1; }
+            done
