updated yml logic
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -58,31 +58,28 @@ jobs:
 
       - name: Save env.prop from Container
         run: |
-          docker cp bateel-automation-demo:/path/to/env.prop ./env.prop || echo "Failed to retrieve env.prop from container."
+          docker cp bateel-automation-demo:/usr/share/HamleysAutomation/env.prop ./env.prop || echo "Failed to retrieve env.prop from container."
+
+      - name: List Files
+        run: |
+          ls -l .
 
       - name: Check if env.prop exists and validate
         run: |
-              if [ ! -f ./env.prop ]; then
-                echo "env.prop file does not exist."
-                exit 1
-              fi
-          
-              if ! grep -q "OperatingSystem=" ./env.prop; then
-                echo "Missing OperatingSystem in env.prop"
-                exit 1
-              fi
-          
-              if ! grep -q "ApplicationURL=" ./env.prop; then
-                echo "Missing ApplicationURL in env.prop"
-                exit 1
-              fi
-
-      - name: Check for Allure Results
-        run: |
-          if [ -z "$(ls -A ./allure-results)" ]; then
-            echo "No Allure results found. Exiting."
-            exit 1
-          fi
+            if [ ! -f ./env.prop ]; then
+              echo "env.prop file does not exist."
+              exit 1
+            fi
+        
+            if ! grep -q "OperatingSystem=" ./env.prop; then
+              echo "Missing OperatingSystem in env.prop"
+              exit 1
+            fi
+        
+            if ! grep -q "ApplicationURL=" ./env.prop; then
+              echo "Missing ApplicationURL in env.prop"
+              exit 1
+            fi
 
       - name: Generate Allure HTML Report
         run: |
@@ -131,8 +128,8 @@ jobs:
 
       - name: Commit and Push Updated env.prop
         run: |
-          git config --local user.email "you@example.com"
-          git config --local user.name "Your Name"
+          git config --local user.email "soham.pandit@krishtechnolabs.com"
+          git config --local user.name "SohamQAKrish"
           git add ./env.prop
           git commit -m "Update env.prop after tests" || echo "No changes to commit"
           git push origin dockerIntegration
