updated YML
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -21,10 +21,10 @@ jobs:
         run: |
           set -x  # Enable debug output
           ALLURE_VERSION=2.20.1
-          wget -q "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}-zip.zip" -O allure.zip || { echo "Failed to download Allure"; exit 1; }
-          
+          wget "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}-zip.zip" -O allure.zip || { echo "Failed to download Allure"; exit 1; }
+            
           unzip -q allure.zip -d allure || { echo "Failed to unzip Allure"; exit 1; }
-          
+            
           sudo mv allure /usr/local/bin/allure
           echo 'export PATH=$PATH:/usr/local/bin/allure/bin' >> $GITHUB_ENV
 
