Updated YML
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -12,6 +12,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Install Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '16' # Specify the Node.js version
+
+      - name: Install Allure CLI
+        run: npm install -g allure-commandline
+
       - name: Build Docker Image
         run: |
           docker build -t bateel-automation-demo:latest .
@@ -29,14 +37,10 @@ jobs:
         run: |
             docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results
         
-      - name: Install Allure Commandline
-        run: |
-              sudo apt-get update
-              sudo apt-get install -y allure # Ensure Allure is installed
-        
       - name: Generate Allure HTML Report
         run: |
-          allure generate ./allure-results --output ./allure-report --clean        
+          allure generate ./allure-results --output ./allure-report --clean
+
       - name: Install sshpass
         run: |
             sudo apt-get update
@@ -48,4 +52,4 @@ jobs:
           PASSWORD: ${{ secrets.SSH_PASSWORD }}  # Store your password as a GitHub secret
           PORT: 2255
         run: |
-              sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-results/* "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload files"; exit 1; }
+              sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/* "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload files"; exit 1; }
