Updated file logic
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -62,20 +62,20 @@ jobs:
 
       - name: Check if env.prop exists and validate
         run: |
-            if [ ! -f ./env.prop ]; then
-              echo "env.prop file does not exist."
-              exit 1
-            fi
-  
-            if ! grep -q "OperatingSystem=" ./env.prop; then
-              echo "Missing OperatingSystem in env.prop"
-              exit 1
-            fi
-  
-            if ! grep -q "ApplicationURL=" ./env.prop; then
-              echo "Missing ApplicationURL in env.prop"
-              exit 1
-            fi
+              if [ ! -f ./env.prop ]; then
+                echo "env.prop file does not exist."
+                exit 1
+              fi
+          
+              if ! grep -q "OperatingSystem=" ./env.prop; then
+                echo "Missing OperatingSystem in env.prop"
+                exit 1
+              fi
+          
+              if ! grep -q "ApplicationURL=" ./env.prop; then
+                echo "Missing ApplicationURL in env.prop"
+                exit 1
+              fi
 
       - name: Check for Allure Results
         run: |
