updated workflow for old report generated
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -1,4 +1,4 @@
-name: Docker Github Integration
+name: Docker GitHub Integration
 
 on:
   push:
@@ -11,9 +11,6 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
-      - name: Install Allure CLI
-        run: npm install -g allure-commandline
 
       - name: Build Docker Image
         run: |
@@ -29,21 +26,9 @@ jobs:
           docker run --name bateel-automation-demo -e DISPLAY=:99 -v /tmp/.X11-unix:/tmp/.X11-unix bateel-automation-demo:latest /bin/sh -c "
           Xvfb :99 -screen 0 1920x1080x24 & DISPLAY=:99 mvn clean test -X"
 
-      - name: Save Allure Report to Local Directory
+      - name: Save Allure Results to Local Directory
         run: |
-              docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results
-
-      - name: Clear Old Allure Reports on Server
-        env:
-          USERNAME: bateel-automation-demo
-          PASSWORD: ${{ secrets.SSH_PASSWORD }}
-          PORT: 2255
-        run: |
-          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "rm -rf /var/www/html/bateel-automation-demo/webroot/*" || { echo "Failed to clear old reports"; exit 1; }
-
-      - name: Clear Old Allure Reports Locally
-        run: |
-          rm -rf ./allure-report/* #cleared report
+          docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results
 
       - name: Generate Allure HTML Report
         run: |
@@ -51,17 +36,37 @@ jobs:
 
       - name: Install sshpass
         run: |
-            sudo apt-get update
-            sudo apt-get install -y sshpass
-        
+          sudo apt-get update
+          sudo apt-get install -y sshpass
+
+      - name: Preserve Existing env.prop on Server
+        env:
+          USERNAME: bateel-automation-demo
+          PASSWORD: ${{ secrets.SSH_PASSWORD }}
+          PORT: 2255
+        run: |
+          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "cp /var/www/html/bateel-automation-demo/webroot/env.prop /tmp/ || true"
+
+      - name: Clear Old Allure Reports on Server
+        env:
+          USERNAME: bateel-automation-demo
+          PASSWORD: ${{ secrets.SSH_PASSWORD }}
+          PORT: 2255
+        run: |
+          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "rm -rf /var/www/html/bateel-automation-demo/webroot/allure-report/*" || { echo "Failed to clear old reports"; exit 1; }
+
       - name: Upload Allure Report to Server
         env:
           USERNAME: bateel-automation-demo
           PASSWORD: ${{ secrets.SSH_PASSWORD }}
           PORT: 2255
         run: |
-              # Clear the old reports on the server
-              sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "rm -rf /var/www/html/bateel-automation-demo/webroot/*" || { echo "Failed to clear old reports"; exit 1; }
+          sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/* "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload files"; exit 1; }
 
-              # Upload new reports
-              sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/* "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload files"; exit 1; }
+      - name: Restore env.prop on Server
+        env:
+          USERNAME: bateel-automation-demo
+          PASSWORD: ${{ secrets.SSH_PASSWORD }}
+          PORT: 2255
+        run: |
+          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "mv /tmp/env.prop /var/www/html/bateel-automation-demo/webroot/ || true"
