Updated files
Signed-off-by: Kashyap Dave <kashyap.dave@krishtechnolabs.local>

diff --git a/.github/workflows/DockerAllure.yml b/.github/workflows/DockerAllure.yml
--- a/.github/workflows/DockerAllure.yml
+++ b/.github/workflows/DockerAllure.yml
@@ -26,12 +26,23 @@ jobs:
 
       - name: Run Tests and Generate Allure Report
         run: |
-          docker run --name bateel-automation-demo -e DISPLAY=:99 -v /tmp/.X11-unix:/tmp/.X11-unix bateel-automation-demo:latest /bin/sh -c "Xvfb :99 -screen 0 1920x1080x24 & DISPLAY=:99 mvn clean test -X"
+          docker run --name bateel-automation-demo -e DISPLAY=:99 -v /tmp/.X11-unix:/tmp/.X11-unix bateel-automation-demo:latest /bin/sh -c "
+          Xvfb :99 -screen 0 1920x1080x24 & DISPLAY=:99 mvn clean test -X"
 
       - name: Save Allure Report to Local Directory
         run: |
-            docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results
-       
+              docker cp bateel-automation-demo:/usr/share/HamleysAutomation/allure-results ./allure-results && \
+              # Clear everything except environment.properties and category.json
+              find ./allure-results -type f ! -name 'environment.properties' ! -name 'category.json' -exec rm -f {} +
+
+      - name: Clear Old Allure Reports on Server
+        env:
+          USERNAME: bateel-automation-demo
+          PASSWORD: ${{ secrets.SSH_PASSWORD }}
+          PORT: 2255
+        run: |
+          sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "rm -rf /var/www/html/bateel-automation-demo/webroot/*" || { echo "Failed to clear old reports"; exit 1; }
+
       - name: Clear Old Allure Reports Locally
         run: |
           rm -rf ./allure-report/*
@@ -45,10 +56,14 @@ jobs:
             sudo apt-get update
             sudo apt-get install -y sshpass
         
-      - name: Upload Allure Report to Docker Container
+      - name: Upload Allure Report to Server
         env:
           USERNAME: bateel-automation-demo
           PASSWORD: ${{ secrets.SSH_PASSWORD }}
           PORT: 2255
         run: |
+              # Clear the old reports on the server
+              sshpass -p "$PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$USERNAME@bateel-automation.magentoprojects.net" "rm -rf /var/www/html/bateel-automation-demo/webroot/*" || { echo "Failed to clear old reports"; exit 1; }
+
+              # Upload new reports
               sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/* "$USERNAME@bateel-automation.magentoprojects.net:/var/www/html/bateel-automation-demo/webroot" || { echo "Failed to upload files"; exit 1; }
